apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
  labels:
    app.kubernetes.io/instance: argocd-example-apps
    app2: changed-from-git
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
